openapi: 3.0.3
info:
  title: Competition-format service
  description: The competition-format service let you administrate the different competition-formats, which are templates for actual events
  version: "1.0"
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
tags:
  - name: competition-format
    description: competition format operations
paths:
  /competition-formats:
    post:
      tags:
        - competition-format
      security:
        - bearerAuth: []
      description: Add a new competition format
      requestBody:
        description: The new format to be created
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CompetitionFormat"
      responses:
        201:
          description: Created
    get:
      tags:
        - competition-format
      description: Get a list of competition formats
      parameters:
        - name: name
          in: query
          description: competition format name
          required: false
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CompetitionFormatCollection"
  /competition-formats/{id}:
    parameters:
      - name: id
        in: path
        description: competition format id
        required: true
        schema:
          type: string
          format: uuid
    get:
      tags:
        - competition-format
      description: Get a unique competition format
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CompetitionFormat"
    put:
      tags:
        - competition-format
      security:
        - bearerAuth: []
      description: Update a competition format
      responses:
        204:
          description: No content
    delete:
      tags:
        - competition-format
      security:
        - bearerAuth: []
      description: Delete acompetition format
      responses:
        204:
          description: No content
  /race-configs:
    post:
      tags:
        - competition-format
      security:
        - bearerAuth: []
      description: Add a new race config
      requestBody:
        description: The new  race config to be created
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RaceConfig"
      responses:
        201:
          description: Created
    get:
      tags:
        - competition-format
      description: Get a list of race configs
      parameters:
        - name: name
          in: query
          description: competition format name
          required: false
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CompetitionFormatCollection"
  /race-configs/{id}:
    parameters:
      - name: id
        in: path
        description: competition format id
        required: true
        schema:
          type: string
          format: uuid
    get:
      tags:
        - competition-format
      description: Get a unique competition format
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CompetitionFormat"
    put:
      tags:
        - competition-format
      security:
        - bearerAuth: []
      description: Update a competition format
      responses:
        204:
          description: No content
    delete:
      tags:
        - competition-format
      security:
        - bearerAuth: []
      description: Delete acompetition format
      responses:
        204:
          description: No content
components:
  schemas:
    CompetitionFormatCollection:
      type: object
      properties:
        events:
          type: array
          items:
            $ref: "#/components/schemas/CompetitionFormat"
    CompetitionFormat:
      properties:
        id:
          type: string
        name:
          type: string
          description: The competition-format's name.
        startingOrder:
          type: string
          description: starting order describing how the start list should be created
        startProcedure:
          type: string
          description: the start procuedure to be used for the event
        max_no_of_contestants_in_raceclass:
          type: integer
          description: maximum number of contestants in raceclass
        max_no_of_contestants_in_race:
          type: integer
          description: maximum number of contestants in race
    RaceConfig:
      properties:
        id:
          type: string
        name:
          type: string
          description: The competition-format's name.

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
